### ISSUE TITLE
Repository name is misleading

### ISSUE THREAD

**Issue by nudzg** [dracula/vim#10]
It would be more appropriate to be something like vim-dracula.

Actual name seems like it is a vim clone from dracula user.

When using vim plugin managers like vim-plug or vundle, cloned repo has the name "vim", which is something really confusing to see.

This naming convention would affect affect other dracula repos, so it seems like a lot of work. I think it applies to the other repos too anyway.

Just my 2 cents...

**Comment by ljani** [comment]
At least [`dein.vim`](https://github.com/Shougo/dein.vim) allows you to name the plugin/repo, which makes it more clear:

```
[[plugins]]
name = 'dracula-theme'
repo = 'dracula/vim'
```

**Comment by heinst** [comment]
@nudzg you could say that about all the repo names then, `dracula/vim-dracula` is pretty redundant

**Comment by dkarter** [comment]
Sorry, I know this issue is closed but I have to agree with @nudzg . Plugin managers install this theme into a folder called `vim` under colors. Two issues I have with that:

1. If other plugins did that all hell will break loose, we'll be looking at a lot of conflicts. 
2. It is really confusing for people who like to be in touch with their `.vim` folder. It seems like some vim system folder exists in colors.

I suggest reconsidering a rename to `vim-dracula` or `dracula-vim` 

Thanks 😊
