### ISSUE TITLE
Vim colors don't seem right, cursorline too dark

### ISSUE THREAD

**Issue by relkochta** [dracula/vim#101]
### What happened

When compared to dracula running in Visual Studio Code, the colors are completely off, plus the cursorline isn't right either.

Screenshot:

![image](https://user-images.githubusercontent.com/38051123/43980485-4d5b8886-9cbc-11e8-82c5-4d07fcc04bf2.png)

### What I expected to happen

Since it's the same color scheme it should look the same or at least fairly similar in different editors

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: neovim, same issue in vim
- **Vim version**: neovim 0.3.0, vim 8.1
- **OS**: Linux earth 4.17.13-gentoo-earth #1 SMP Wed Aug 8 13:07:54 EDT 2018 x86_64 AMD Ryzen 7 2700X Eight-Core Processor AuthenticAMD GNU/Linux
- **Terminal/Terminal Emulator/VTE**: rxvt-unicode, VTE 0.48.4
- **`TERM` environment variable**: rxvt-unicode-256color

I know this is my second opened issue today, but no matter which settings I change I can't seem to get it right. here's my init.vim:

![image](https://user-images.githubusercontent.com/38051123/43980576-ae8b6c84-9cbc-11e8-9bb1-c86fad648307.png)

**Comment by Lightn1ngStr1ke** [comment]
To clarify, the bottom is VSCode and the top is NeoVIM.

**Comment by Lightn1ngStr1ke** [comment]
Interestingly enough, when installing with the same configuration on MacOS with iTerm2, it yields the same result.

Using the default configuration without t_co, colorterm, etc... set results in:

![image](https://user-images.githubusercontent.com/38051123/43983075-bc9da72e-9cc6-11e8-9e77-5e2e6fb4f3ce.png)

**Comment by dsifford** [comment]
@Lightn1ngStr1ke It's your lucky day. I maintain both the VSCode Dracula **and** the Vim Dracula theme :stuck_out_tongue_closed_eyes: 

Unfortunately, the issues you're pointing out are issues/limitations with syntax implementations across the editors. VSCode's syntax (which is a derivative of textmate) is much more robust than the syntax that Vim provides. So, because of that, syntax definitions are able to get much more detailed.

Speaking specifically to the discrepancies you've pointed out:

- Python classes and magic methods in Vim are scoped identically to functions, so that's why they're green.
- Python magic methods are also scoped id
- `self` and `cls` are able to be fixed. I'll add that on the todo list....

---------

**Some other notes:**
- Try using `syntax enable` rather than `syntax on`
- iterm is finnicky. I use a macbook as my secondary machine and I needed to explicitly set TERM in my iterm config to a supported 256-color terminal (which, on my machine, happened to be a custom `tmux-256color`).

**Comment by Lightn1ngStr1ke** [comment]
@dsifford Thanks so much for all the information and help! I just wanted to confirm that nothing was wrong - the colors in vim seem to work well enough.

Any ideas about the cursorline issue? It seems to work with termguicolors in iTerm, but no dice on rxvt-unicode.

**Comment by Lightn1ngStr1ke** [comment]
@dsifford

May I ask what terminal emulator you use on Linux that it works under?

**Comment by benknoble** [comment]
`gnome-terminal` on Ubuntu works with `termguicolors` (but not inside `tmux`)

**Comment by benknoble** [comment]
I'm going to close this since I'm not sure there's any way to make forward progress at the moment. Feel free to reopen if something changes that makes it easier to bring VS Code/vim into alignment.
