### ISSUE TITLE
Incorrect background and text color in terminal

### ISSUE THREAD

**Issue by alexsmth** [dracula/vim#164]
I am experiencing the following problems running the dracula theme in macOS Catalina.Posting results with and without termguicolors set in vimrc.

### What happened
Background color and colors in general are way off than the preview pictures

### Screenshot
<img width="570" alt="Screenshot 2019-12-27 at 8 55 14 PM" src="https://user-images.githubusercontent.com/36931941/71528999-3e8bdb00-28eb-11ea-9572-bd8ceb399f70.png">

<img width="570" alt="Screenshot 2019-12-27 at 8 56 35 PM" src="https://user-images.githubusercontent.com/36931941/71529031-6418e480-28eb-11ea-9c8a-475a5ee3e0e9.png">
### Machine Info
Macbook air 2019 
MacOS Catalina v10.15.2

**Comment by benknoble** [comment]
The second image looks fine to me; what vim are you running? Terminal or MacVim? What version?

If you run in Terminal.app, you don't want `termguicolors` because Apple's Terminal.app doesn't support 24-bit color.

In the gui, gui colors will be applied, and you don't care.

There is also, as documented, the following configuration variable:

```
* *g:dracula_colorterm*
Include background fill colors >
   let g:dracula_colorterm = 1
```

[The screenshot is from 2016 or earlier](https://github.com/dracula/dracula.github.io/commits/d96b16627c0ff12d7ccb28d382763b72b0d5e3ed/src/assets/img/screenshots/vim.png)

**Comment by benknoble** [comment]
FWIW, here's a comparable screenshot I just took (yes, typing in all that text was painful).

<img width="1227" alt="dracula:vim (mac and terminal; custom statusline; term includes cursorline:number)" src="https://user-images.githubusercontent.com/22802209/71549122-2a48ec00-2986-11ea-9e89-7b025942e05c.png">

(mac & terminal; custom statusline; term includes cursorline+number; term also uses dracula/terminal-app)

@dsifford what say you to updating the screenshot?

**Comment by alexsmth** [comment]
Thank you very much.Added the following lines in my vimrc and it worked like a charm.

_let g:dracula_colorterm = 0
let g:dracula_italic = 0_
