### ISSUE TITLE
html tags color white in JSX syntax

### ISSUE THREAD

**Issue by Groude** [dracula/vim#193]
### What happened
JSX syntax does not highlighting tags properly:
![Screenshot from 2020-05-29 15-31-44@2x](https://user-images.githubusercontent.com/5012405/83260068-ce4af380-a1c1-11ea-92a6-7f81c82ec422.png)
### What I expected to happen
Tags should not be a white color

### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**: Vim
- **Vim version**: 8.0.1453
- **OS**: Elementary OS
- **Terminal/Terminal Emulator/VTE**: tmux
- **`TERM` environment variable**: xterm-256color

Is that a bug? or it's normal that tags color white inside JSX syntax

**Comment by dsifford** [comment]
What syntax plugins are you running?

**Comment by Groude** [comment]
@dsifford vim-polyglot

**Comment by dsifford** [comment]
I assume your case is probably the result of some plugin included in polyglot.

Maybe @benknoble uses that plugin and can provide insight.

**Comment by Groude** [comment]
this is how it looks without vim-polyglot:
![Screenshot from 2020-05-29 15-49-41@2x](https://user-images.githubusercontent.com/5012405/83261496-1a973300-a1c4-11ea-8428-43afbc16be1f.png)

**Comment by dsifford** [comment]
I use pangloss/vim-javascript and HerringtonDarkholme/yats.vim, but rarely write javascript that isn't typescript.

**jsx:**

![image](https://user-images.githubusercontent.com/5240018/83261967-2fef6b80-a18a-11ea-8818-2188559951d0.png)

**tsx:**

![image](https://user-images.githubusercontent.com/5240018/83262031-4dbcd080-a18a-11ea-95fd-d0f55828300a.png)

Obviously, there's some discrepancies here, but that's just the nature of vim syntax unfortunately. Neovim is on the cusp of implementing tree-sitter, which should make this a whole lot better.

**Comment by benknoble** [comment]
Vim will get a tree-sitter soon too, I hope, now that text-properties have been implemented.

I don't use polyglot (too much bloat, and frequently causes other issues). But I do use pangloss/vim-javascript (though I don't write any jsx at the moment).

The vim runtime has `syntax/javascriptreact.vim` whose contents are

```
" Placeholder for backwards compatilibity: .jsx used to be associated with the
" filetpye JavaScript.
runtime! syntax/javascript.vim
```

**Comment by Groude** [comment]
tsx works well for me too after I added this option to my .vimrc:

`let g:vim_jsx_pretty_disable_tsx = 1`

now it looks like this: 
![Screenshot from 2020-05-29 16-50-39@2x](https://user-images.githubusercontent.com/5012405/83267541-0ad01c80-a1cd-11ea-8517-9933228e3d46.png)

Maybe it's should be way for jsx too...

Struggling this issue only with Dracula coloscheme :(

**Comment by Groude** [comment]
@benknoble @dsifford 

I don't why but with this plugin: https://github.com/mxw/vim-jsx

jsx, tsx looks fine!

**Comment by benknoble** [comment]
@Groude If that solves your problem, we can probably close this for now and point people to that plugin for j/tsx

**Comment by moQuez** [comment]
I've been struggling with the same as @Groude..., using mxw/vim-jsx kinda looks better but it is not a 1:1 match with tsx...

.tsx:

<img width="843" alt="Screenshot 2020-06-11 08 14 51" src="https://user-images.githubusercontent.com/26433/84384552-261f2c80-abbc-11ea-9482-d37f2d362ca6.png">

.jsx: (please ignore the ts typing errors...)
<img width="847" alt="Screenshot 2020-06-11 08 18 32" src="https://user-images.githubusercontent.com/26433/84384556-27505980-abbc-11ea-97c0-c37e5775fc25.png">

**Comment by benknoble** [comment]
@moQuez yeah that's going to be an issue as long as vim's syntax engine is based on regex, groups, and a few other mechanisms: it's too much work to get it perfect for every language. Worse, though this is unrelated to choice of engine, there's no *real* standard for what to link what elements to. I mean, sure, there's `:help highlight-groups`, but even then people disagree about what to use, as you've shown.

**Comment by moQuez** [comment]
I agree it would be a lot of work. However, do you think it'll be possible to have like a "per-syntax-plugin" dracula override?

I'd imagine something like `vim-polyglot-dracula`, were it would be a repo for using dracula for each of the default syntax highlighters on vim-polyglot. Each polyglot entry having its own "package" and, possibly, with independent maintainers. That way, anyone having these issues is welcome to fix it for him (like me or @Groude ) and possible for other dracula users.

Question is... Would that be technically feasible?

**Comment by dsifford** [comment]
@moQuez We sort of already do that in this repo. 

See here: https://github.com/dracula/vim/tree/master/after/syntax

**Comment by moQuez** [comment]
Oh! Let me see if I can manage to fix JSX like it is done here: [https://github.com/dracula/vim/blob/master/after/syntax/typescriptreact.vim](https://github.com/dracula/vim/blob/master/after/syntax/typescriptreact.vim)

I'll give it a shot after the workday is off (kinda tired of my JSX looking funny)

Thanks!

**Comment by moQuez** [comment]
Hey guys! I've been going over this and I think I have the solution. Basically is just doing several links like this on the javascript syntax. Basically watching out what vim-jsx-pretty exposes and working on top of it...

```
hi! link jsxComponentName       Type
```

However, I just noticed something really weird. Basically by the time the Dracula syntax scripts load, the b:current_syntax variable is not present. Therefore I always reach the `dracula#should_abort()` function.

I do have the `syntax enable` flag on my vimrc. And when I do `echo b:current_syntax' inside a js file I get the right `javascript` value.

Any clues?

**Comment by benknoble** [comment]
that's... odd. Not sure what could be the issue there. I assume you're starting a new vim instance to test your changes?

**Comment by moQuez** [comment]
yes, each time. I actually inserted an `echo b:current_syntax` on `autoload/dracula.vim` and each time I open up a new instance (by opening a js file) it actually fails, saying it doesn't exist.

**Comment by benknoble** [comment]
hm: could be that syntax is enabled in an order that's causing issues? I would try to bisect your config until you get a reliable environment or you find the issue.

**Comment by moQuez** [comment]
Well finally got an environment that kinda "works"... 

However, I'm trying to make vim-jsx-pretty to play nice with Dracula. As pointed out before, when it loads, it sets the `echo b:current_syntax` to `javascript.jsx`...

I tried adding a `syntax/javasript.jsx.vim` file, but it doesn't seem to be getting picked up by vim automatically...

I am no vim expert but is seems as the after/syntax/<language> depends on the value of `set filetype?` which in case of vim-pretty-jsx is not using any conventional one, `but javascript.jsx` instead.

I managed to get it working by changing the initial if statement:

<img width="772" alt="Screenshot 2020-06-18 08 06 06" src="https://user-images.githubusercontent.com/26433/85018263-e2d43900-b13a-11ea-93bc-307a33224198.png">

Now the get the real jsxComponentName link... And it looks as it should:

<img width="639" alt="Screenshot 2020-06-18 08 08 32" src="https://user-images.githubusercontent.com/26433/85018306-f8496300-b13a-11ea-89c6-4ec9e1455ac5.png">

Now that I now how to work around what maxmellon/vim-jsx-pretty gives us, I'll try to match as much as how a jsx file ends up looking in VSCode.

I'll put in a PR later today :)

**Comment by dsifford** [comment]
That `&&` is not going to be able to fly here. I don't have time at the moment, but it is more than likely a mistake on the end of the jsx plugin developer you are using.

What _should_ happen is that javascript should load first, then it should load the `syntax/javascript.vim`, then it should set the current syntax to `javascriptreact` and then load `syntax/javascript.vim` -- `javascript.jsx` is not a thing anymore (it used to be but now vim decided to make `javascriptreact` the filetype for jsx.

**Comment by dsifford** [comment]
The reason why it works for you with the `&&` is because it effectively will make that condition never evaluate to true.

**Comment by moQuez** [comment]
> That `&&` is not going to be able to fly here. I don't have time at the moment, but it is more than likely a mistake on the end of the jsx plugin developer you are using.
> 
> What _should_ happen is that javascript should load first, then it should load the `syntax/javascript.vim`, then it should set the current syntax to `javascriptreact` and then load `syntax/javascriptreact.vim` -- `javascript.jsx` is not a thing anymore (it used to be but now vim decided to make `javascriptreact` the filetype for jsx).

Yes my initial thoughts exactly. But I wasn't sure if putting the blame on vim-jsx-pretty was appropriate. Now that would make much more sense. I'll go ahead and take that into consideration and use a proper `syntax/javascriptreact.vim` file.

Thanks for taking the time into clarifying this for me

**Comment by benknoble** [comment]
2cents: `javascript.jsx` is a way of including multiple syntaxes (works for filetypes too) bu separating them with dots (.).

**Comment by dsifford** [comment]
@benknoble Yep, but for jsx specifically, this is not how it's done. 

I actually was pretty upset when vim decided this and (IIRC) voiced my opinion on the matter when it happened, but they (vim core maintainers) chose to go with `javascriptreact` and `typescriptreact` instead.

**Comment by dsifford** [comment]
In fact, you might remember back when _this_ repo had syntaxes that supported `javascript.jsx` and `typescript.tsx` back about a year ago before vim made the decision on `javascriptreact`/`typescriptreact`

**Comment by benknoble** [comment]
Yes; not trying to bring up those debates again! Just informing @moQuez about an « unusual » filetype :)

**Comment by renatoagds** [comment]
@moQuez do you still working on this? if no, I would like to help, I'm experiencing the same problem.

**Comment by moQuez** [comment]
> @moQuez do you still working on this? if no, I would like to help. I'm experiencing the same problem.

I'm sorry for going silent on this one... Yes, I did some work on this and got to a pretty comfortable state. This is how it looks so far:

![Screenshot 2020-06-30 17 29 14](https://user-images.githubusercontent.com/26433/86178860-28a7de80-baf7-11ea-9299-b706cad24c54.png)

I haven't made a PR yet because I am unsure about how to go around the filetype thing.

As `vim-jsx-pretty` is the one responsible for reporting the filetype, it is outside the scope of this repo. In any case, with the current filetype reported (javascript.jsx) I do have a solution which you can check out here: [https://github.com/dracula/vim/compare/master...moQuez:master](https://github.com/dracula/vim/compare/master...moQuez:master)

@benknoble @dsifford, dunno if you'd agree on having this portion supporting plugins reporting the old filetype, or you'd rather push everyone to report the same as vim (javascriptreact). (Which now that I've read and understood the whole thread, it was kinda pointless to change it).

**Comment by dsifford** [comment]
@moQuez Not sure I understand your question. But if I am understanding you correctly, yes, I'd much prefer plugins to just support the standard `javascriptreact` filetype than have to account for this ourselves.

In other words, `vim-jsx-pretty` should fix on their end.

**Comment by moQuez** [comment]
Yes precisely what I thought. Therefore, until `vim-jsx-pretty` catches up, I'll just work with my branch. @renatoagds  you are welcome to use and contribute to that branch.

**Comment by dsifford** [comment]
I'd recommend also opening an issue in jsx-pretty if one doesn't already exist for this.

**Comment by dsifford** [comment]
Well this is interesting...

![image](https://user-images.githubusercontent.com/5240018/86276675-49c60900-bba3-11ea-8656-4779e1a36081.png)

Looks like they already do support those filetypes... What gives?

**Comment by moQuez** [comment]
The underlying issue is that no one identifies jsx as javascriptreact...

`vim-javascript` doesn't do it... and `vim-jsx-pretty` only adds the suffix, but no one actually sets the filetype to javascriptreact

**Comment by dsifford** [comment]
Vim should be what does this...

**`javascriptreact`**: https://github.com/vim/vim/blob/1112c0febb509d0cb219f3a2479fd36833507167/runtime/filetype.vim#L812-L813

**`typescriptreact`**: https://github.com/vim/vim/blob/1112c0febb509d0cb219f3a2479fd36833507167/runtime/filetype.vim#L1762-L1763

**Comment by renatoagds** [comment]
@dsifford Looked deep into the problem and got @moQuez point.

The point is that `vim-jsx-pretty` force `b:current_syntax` for `javascript.jsx` here: https://github.com/MaxMEllon/vim-jsx-pretty/blob/master/after/syntax/javascript.vim#L52

They're doing that to avoid breaking the plugins ecosystem that's using `javascript.jsx`, as pointed for one of the `vim-jsx-pretty` committer in https://github.com/vim/vim/issues/4830

The other point is that vim only set the filetype for `javascriptreact` in `.jsx` (same for `typescriptreact`), and even in this cases, `vim-jsx-pretty` changes `current_syntax` to `javascript.jsx`.

So, if you're opening a `.js` file, that contains `jsx` syntax, the `filetype` will be settled as `javascript` but `current_syntax` will be `javascript.jsx` and since we're checking `current_syntax` against `javascript` only, it fails and abort.

Based on this scenario, suggest following this way:

- Create `javascriptreact.vim` that only loads `javascript.vim` (following what `vim-jsx-pretty` does - https://github.com/MaxMEllon/vim-jsx-pretty/blob/master/after/indent/javascriptreact.vim)

- Change `typescriptreact.vim` to only loads `typescript.vim`, moving it handlers to `typescript.vim` (following what `vim-jsx-pretty` does - https://github.com/MaxMEllon/vim-jsx-pretty/blob/master/after/indent/typescriptreact.vim)

- Support `typescript.jsx` and `javascript.tsx` in `typescript.vim` and `javascript.vim`, since the ecosystem still in top of this and probably will take a time to move on.

- Support `vim-jsx-pretty` syntax group list (https://github.com/MaxMEllon/vim-jsx-pretty#syntax-group-list) in `javascript.vim`

This way, we will have a full support in top of `vim-jsx-pretty` and support `*.js,*.ts` (that's using JSX) plus `*.jsx,*.tsx` files.

Sounds good?

**Comment by moQuez** [comment]
Sound good to me...

The last 2 bullets are the ones that I've been working on my branch @renatoagds, maybe we could join our efforts into wrapping all that up.

**Comment by dsifford** [comment]
I feel like this is still something that should be addressed by the vim-jsx-pretty author.

It's fine that they are setting the filetype to javascript.jsx, but if they expect jsx syntax and ftplugins to load in that case, they should call `runtime! syntax/javascriptreact` and `runtime! ftplugin/javascriptreact` as well because they are effectively saying "this file is now jsx".

That seems to me like the logical way to address this.

**Comment by renatoagds** [comment]
> It's fine that they are setting the filetype to javascript.jsx

@dsifford They're not changing the filetype, they're changing the `current_syntax`. The filetype still `javascript` and `javascriptreact`, but since we abort if the `current_syntax` is different than `javascript.jsx`, it fails.

**Comment by dsifford** [comment]
So just so I'm understanding you correctly, just adding `javascript.jsx` to should_abort would be the only change necessary in this repo?

If so, that's reasonable.

**Comment by renatoagds** [comment]
@dsifford IMO, the changes should be these ones:

- Support `vim-jsx-pretty` syntax group list (https://github.com/MaxMEllon/vim-jsx-pretty#syntax-group-list) in `javascript.vim`

- Create `javascriptreact.vim` that only loads `javascript.vim`, since the JSX styling is already included in `javascript.vim`, since `.js` files that includes JSX code has their filetype as `javascript`.

- Move JSX styling from `typescriptreact.vim` to `typescript.vim`, since `.ts` files that include JSX code still having their typefile as `typescript`.

- Change `typescriptreact.vim` to only loads typescript.vim.

- Allow `typescript.tsx` and `javascript.jsx` in `should_abort`.

Did I explain better @dsifford ?

**Comment by dsifford** [comment]
Yep, that sounds reasonable. Thanks @renatoagds

**Comment by renatoagds** [comment]
@dsifford @moQuez and @Groude take a look at #198 

Took the points from here and first commits from @moQuez and arrived in this one.
