### ISSUE TITLE
Parameters should be orange italic

### ISSUE THREAD

**Issue by PitcherTear22** [dracula/vim#195]
### What happened
Function/method parameters are white
### What I expected to happen
Function/method parameters are orange italic - [spec](https://spec.draculatheme.com/#sec-Functions-Methods)
Screenshot (https://draculatheme.com/static/img/screenshots/visual-studio-code.png)
### Screenshot
https://draculatheme.com/static/img/screenshots/vim.png
### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**:
- **Vim version**:
- **OS**:
- **Terminal/Terminal Emulator/VTE**:
- **`TERM` environment variable**:

**Comment by benknoble** [comment]
I'll leave @dsifford to weigh in here, but these types of differences are unfortunately commonplace: VS code and vim have completely different syntax engines under the hood, and aligning them perfectly is Sisyphean. We will *probably* make a lot of progress there if text-properties lead to tree-sitter based syntax engines, but that doesn't seem to be a priority for anyone atm.

**Comment by PitcherTear22** [comment]
I almost finished the java parser : https://github.com/nvim-treesitter/nvim-treesitter/commit/79556b4155d84d22bc1c4a3b56c6407bdc9e2eff

**Comment by vigoux** [comment]
Hi everyone, sorry to come up here. One thing we can do is provide some new highlight group that will default to normal (thus those will be specific to neovim), and we can later link them to their correct color. I am thinking of `treesitterArgument` being linked to `DraculaOrangeItalic` for example.
This is highly related to `nvim-treesitter`, and thus I don't really think that the discussion should take place here but more at `nvim-treesitter` repo.

**Comment by dsifford** [comment]
@benknoble Yeah, unless the groups for Javascript have changed recently which allow for the arguments to be targeted specifically (which could be possible, I haven't checked in a while), there's not much we can do here about that.

**Comment by benknoble** [comment]
Based on comments, there may be a solution at the neovim level (or a solution at that level that allows a solution for dracula), but I'm at least somewhat reluctant to fragment the theme too much. We already have to do quite a bit to support "everyone's favorite plugin/language pack/..."

"Vanilla" vim doesn't have treesitters that neovim is working on, at least AFAIK (I don't keep up too well with its dev cycles at the moment). This is my opinion, but until tree-sitter-like solutions become unified, I would rather stick to the current "standard" method (am I too optimistic thinking the tree-sitter interfaces will unify? perhaps...). Otherwise, we have to a big "if nvim with treesitter: also define this other stuff"—more work to code, more to maintain, etc. I'm not totally opposed if it's needed to fix some particularly grievous issues, but right now it seems like we may not be at the necessary level, either of support for tree-sitter-syntax or of need for adding it to colorschemes.

Hopefully this reads somewhat ok; I know I'm kind of rambling as I try to figure out how to handle something like this.

**Comment by benknoble** [comment]
In fact, it would be helpful to know if there are other popular colorschemes that target neovim's tree-sitter stuff currently

**Comment by vigoux** [comment]
I completely agree to your point. One thing to note though is that there is already some neovim specific highlighting in Dracula. Thus if (and only if) those modifications with treesitter gets up streamed, will it be reconsidered?

**Comment by benknoble** [comment]
@vigoux I’d completely forgotten about the nvim LSP stuff—I’m totally fine for things in neovim to be themed here (it’s the best solution given that practically no syntax files actually link everything to the core highlight groups). Of course, that will end up being effort to try to maintain as consistent an experience as is humanly possible across the vims... as long as it doesnt become a mess where we color two vim/nvim elements differently arbitrarily, it might be feasible. One concern is getting a bunch of issues like « my vim doesnt look like this screenshot » that just turn out to be editor differences—we get a lot of those (and I understand why! the landscape is confusing), but I feel like I keep explaining it and turning people away somewhat unsatisfied.

**Comment by benknoble** [comment]
Short-term, can we take the tree-sitter/other nvim stuff to separate issue(s)? I want to get OP a straightforward answer to this issue (which it looks like is « we cant fix this atm, sorry) and resolve it.

**Comment by vigoux** [comment]
Then why not having a vim and a neovim version of the colorscheme?

**Comment by dsifford** [comment]
It’s my preference to not fracture this theme into 2 projects. It’ll be easier to keep uniform if it’s all in one

**Comment by vigoux** [comment]
As this discussion is not going anywhere further than philosophical editor wars, I think that you can close that.
The point I am trying to raise here is that if the problem is maintaining things for both vim and neovim (which will for sure become harder and harder), then why not splitting things into two themes, one for vim and one for neovim?
I get that for some people it can be confusing, but hey, why don't you know the name of the editor you are using after all?

**Comment by vigoux** [comment]
And to conclude, I would be glad to maintain the neovim version if no-one wants to, I am using Dracula for everything, loving this theme, and I use neovim quite heavily...

**Comment by vigoux** [comment]
> It’s my preference to not fracture this theme into 2 projects. It’ll be easier to keep uniform if it’s all in one 

Then close this, and if this issue gets upstreamed, I will open a pr to bring the modifications here.

**Comment by dsifford** [comment]
@vigoux It sounds like you're frustrated, which I'm not sure why, but just to reiterate: @benknoble and I are not opposed to targeting nvim highlight groups in this project if it is needed to maintain a uniform experience.

We should not, however, target them and spruce them up just because we _can_. If the default groups are linked to groups that we already highlight, and those defaults make sense. We should not target them again.

Feel free to open a PR if you noticed any particular issue. We are both very open and welcome to changes that improve the theme or better align it with the spec.

**Comment by vigoux** [comment]
Sorry for the tone! I did not wanted to sound like this at all!
Before doing any modification to the theme, a great effort of stabilization needs to be done on our side, which we will pull back here afterwards! Now you can close this issue, as it does not (in my opinion) correspond to any particular problem on your side

**Comment by PitcherTear22** [comment]
Closing as requested by @benknoble and @vigoux
