### ISSUE TITLE
Directory not found in 'packpath': "pack/*/opt/dracula"

### ISSUE THREAD

**Issue by loohoo** [dracula/vim#203]
env: 
os: window linux sub system  debian
vim version : 8.0
install method: vim-plug

then
```
Directory not found in 'packpath': "pack/*/opt/dracula"
```
come out

**Comment by benknoble** [comment]
@dsifford I don't have much time to sink on this, but I know we need more details from the OP if we're going to be able to help.

**Comment by BonitaTerror** [comment]
The packpath might not be where you think it is. I made that mistake at first and had a result similar to what you are describing. In vim run `:echo $VIM` to see what directory your pack directory should be in

**Comment by benknoble** [comment]
@BonitaTerror eh, I wouldn't recommend putting user packages under the system installation—unless you are the sysadmin or similar, the absolute *best* way to go is to try `:help 'packpath'` and `:set packpath?` to see where to put your packages. I put mine in `~/.vim/pack/.../` with no issues whatsoever (because `~/.vim` is on my `packpath`).

**Comment by benknoble** [comment]
I'm going to close this as we haven't seen any updates from the OP and we haven't been able to make progress based on what we have—if we get more details, we can reopen and reinvestigate.
