### ISSUE TITLE
Multiple problems while using with neo vim in windows terminal.

### ISSUE THREAD

**Issue by phantom2152** [dracula/vim#236]
### What happened
While using dracula with neovim in windows the windows terminal splits into two colors when minimized and maximized and color does not cover entire screen
 
### What I expected to happen
The colors should be same across the terminal 
## Screenshot of inti.vim
![image](https://user-images.githubusercontent.com/70034285/112513802-b5e43f00-8dba-11eb-8a8e-67ad87690a5d.png)

### Video of the error
https://user-images.githubusercontent.com/70034285/112512998-ea0b3000-8db9-11eb-96ed-8a5088557aca.mp4

### Machine Info

- **Vim type (`neovim`)**:
- **Vim version**: NVIM v0.4.4
- **OS**: Windows 10 20H2
- **Terminal/Terminal Emulator/VTE**: Windows terminal
- **`TERM` environment variable**:

**Comment by benknoble** [comment]
1. [Please don't post images of text](https://benknoble.github.io/blog/2019/11/24/pics-text/)
2. That looks more like a terminal problem than a dracula or even a vim problem. 

The first thing I see is that when you scroll you're scrolling between what looks like screen buffers, not scrolling the actual file open in vim. So that's not something I know how to fix, but it's not really relevant here.

The second thing I notice is that vim didn't react nicely to the changes in terminal size (esp. small -> large). Again, that's a terminal issue and doesn't have any bearing here, which is specifically for dracula/vim. It seems like vim is not correctly detecting terminal changing size (you might ask vim what it thinks `columns` is, for example).

So, unless this is really focused on dracula/vim and this *only* happens with the dracula colorscheme (hint: try `vim -Nu NONE` or `vim --clean`; I would be shocked if your problems suddenly went away), I'm going to close this.
