### ISSUE TITLE
Support for .sol Ethereum Solidity source code

### ISSUE THREAD

**Issue by AdamBD** [dracula/vim#243]
Hi all,

Anyway to build out support for solidity source code filetypes?

**Comment by dsifford** [comment]
Per this answer posted on stackexchange by @benknoble https://vi.stackexchange.com/a/22407 --- Vim doesn't currently ship with the solidity filetype.

So in order to do this, you'd either have to download a plugin that provides that or write one yourself.

From there, if there are any adjustments needed to align with the spec, we can then talk about adding them to this repo.

**Comment by benknoble** [comment]
Hm, I guess I've hit that point where other people are citing my answers 😅

But yes, if there is a plugin whose filetype highlights need some adjustments, we can discuss. Here is emphatically _not_ the place to put syntax files or filetype-detection for a language.

**Comment by benknoble** [comment]
Closing this; we can reopen if discussion merits or handle a new issue.
