### ISSUE TITLE
Need better installation instructions for Windows

### ISSUE THREAD

**Issue by benknoble** [dracula/vim#244]
See [this QA](https://stackoverflow.com/q/67015374/4400820) with a response from @romainl, who also points out a potential issue with our `packadd!` instructions. (They are necessary because of #138 #139 #140 #142.)

**Comment by romainl** [comment]
So you managed to drag me into this after all…

You should move your palette variables from `autoload/dracula.vim` to `colors/dracula.vim`.

By doing that, you:

- remove the dependency to `autoload/dracula.vim` from `colors/dracula.vim`,
- so you don't need to have  `dracula` in `&rtp`,
- so you don't need `packadd! dracula` in your `vimrc`,
- and you don't break the Airline and Lightline themes because the variables are defined long before they are sourced.

**Comment by benknoble** [comment]
Sorry romainl; if you're not interested, I suppose you can unsubscribe. The airline issue arose when someone installed the colorscheme but did not activate it and attempted to activate the corresponding airline theme.

Do you have a better suggestion to avoid the duplication that doesn't involve the runtimepath? I suppose some `<sfile>:h` trickery might work.
