### ISSUE TITLE
Some text seems to just render white

### ISSUE THREAD

**Issue by seanbourkemckenna** [dracula/vim#254]
![image](https://user-images.githubusercontent.com/19666202/121971951-dac0d080-cd71-11eb-929c-e1443890e631.png)

![image](https://user-images.githubusercontent.com/19666202/121972083-27a4a700-cd72-11eb-8c53-cb91ffadcacd.png)

same code in VSCode with Dracula theme

![image](https://user-images.githubusercontent.com/19666202/121972243-7eaa7c00-cd72-11eb-8c7a-767202965170.png)

Shouldn't the right hand side be the same as the left on top image?

I've set termguicolors

Using iTerm $TERM=xterm-256color

**Comment by benknoble** [comment]
Is this javascript?

VsCode uses more complete syntax highlighters in the form of tree-sitters. 

Vim's default js syntax is lacking. There's a popular replacement by pangloss. But even that is lacking some things. 

Without using tree-sitters, there is likely to be some discrepancy--even if you took the time to rigorously implement the whole grammar for the language, I believe tree-sitters permit some semantic analysis. 

NeoVim is getting native tree-sitters soon (@dsifford may have more info). In Vim, you'll have to look for syntax plugins or write your own. We do try quite hard to keep things aligned, but it cannot be perfect because of the feature discrepancies. 

There are some related issues.

**Comment by seanbourkemckenna** [comment]
Thanks for the context @benknoble!

It's Typescript

I managed to find this in the meantime which improves on pangloss a bit https://github.com/vieira/vim-javascript

Interesting news about NeoVim and tree-sitters! I did find this also https://github.com/nvim-treesitter/nvim-treesitter

Will give this a shot 👍

**Comment by benknoble** [comment]
Thanks for the reply! I'll close this unless/until it needs re-opened. That fork looks interesting!
