### ISSUE TITLE
Vim color issue with js, ts

### ISSUE THREAD

**Issue by tranduchuy** [dracula/vim#257]
![image](https://user-images.githubusercontent.com/7942693/126883799-26b979f4-c84e-43d0-ad65-54cfd44b1346.png)
![image](https://user-images.githubusercontent.com/7942693/126883832-7c7cbe65-5d9c-45ac-993e-a2264695e42a.png)

Hi everyone, I have a trouble highlighting with js, ts files like this. Does any one know how to fix it?
Thank you so much

**Comment by benknoble** [comment]
This looks related: https://github.com/dracula/vim/issues/219

If you don't have a terminal supporting italics, you can do `let g:dracula_italic = 0` prior to loading the colorscheme. Otherwise you should make sure your terminal supports italics and that sends the correct sequences for them (check `$TERM`, `terminfo`, &c.)

**Comment by tranduchuy** [comment]
@benknoble Thanks, it works!
