### ISSUE TITLE
How can change from highlight to default especially ?

### ISSUE THREAD

**Issue by ma-chang** [dracula/vim#269]
I just installed dracula by vim-plug, but I don't  wanna use hightlight color for variable and others like picture below.
If is a problem of config or others?
If you have any way to fix, please tell me.
<img width="379" alt=" 2021-11-12 22 39 08" src="https://user-images.githubusercontent.com/8191520/141478158-1284af59-b58c-40b9-af18-1855b910684a.png">

<img width="332" alt=" 2021-11-12 22 48 32" src="https://user-images.githubusercontent.com/8191520/141478169-7684a2f4-bed2-43c8-a9ee-07668bea1640.png">

**Comment by benknoble** [comment]
I'm not sure what exactly you want to change, but if it's the reverse color, that's because your terminal doesn't support (or isn't configured correctly to support) italics. Try `let g:dracula_italic = 0` before loading the colorscheme.

If on the other hand you want to simply disable certain highlights, that's harder, but here's how I create a "minimal" colorscheme from an existing one:

```vim
" TODO rewrite with `hlset()` when patch 8.2.3578 is available
function s:minimal_colors()
  " edit this list with groups you want to clear
  for group in ['Identifier', 'Function', 'Statement', 'Conditional', 'Repeat',
        \ 'Label', 'Operator', 'Keyword', 'Exception', 'PreProc', 'Include',
        \ 'Define', 'Macro', 'PreCondit', 'StorageClass', 'Structure',
        \ 'Typedef', 'Tag', 'Debug']
    execute 'highlight clear' group
  endfor
endfunction

if has('autocmd')
  augroup minimal_syntax
    autocmd!
    autocmd ColorScheme * call s:minimal_colors()
  augroup END
endif
```

Otherwise you could try disabling syntax highlighting (which won't disable UI colors like line numbers) with `:syntax disable` (or never putting `:syntax enable` in your config).

Lastly under `:help dracula-customization` there is a documented method of customizing any of the highlighting you want.

**Comment by ma-chang** [comment]
@benknoble Thank you for replying so fast!
I tried insert `let g:dracula_italic = 0` before loading the colorscheme in .vimrc and fixed it.
If I will have some other problem in dracula/vim, I use `:help dracula-customization ` to try to fix by myself.
