### ISSUE TITLE
How to change shade of green

### ISSUE THREAD

**Issue by norogoth** [dracula/vim#279]
Hello, looking for a way to just change the shade of green used in dracula. I am not seeing any hex colors in the dracula.vim file so I am unsure how those colors are pulled in. I would like to set my own hex color.

Thanks for the plugin!

**Comment by benknoble** [comment]
The simplest option is probably something like (`:help dracula-customization`)
```vim
augroup tweak_dracula_green
  autocmd!
  autocmd ColorScheme dracula higlight DraculaGreen …
augroup end
```
but watch out for `DraculaGreenBold`, `…Italic`, and `…ItalicUnderline`. (Also `DraculaSearch` and `MatchParen`.)

The colors are defined in `autoload/dracula.vim`. Short of modifying the source, I'm not sure of a way to tweak those (and typically modifying the source is a work-intensive effort, _e.g._, because of updating).
