### ISSUE TITLE
The highlighting of diagnostics should not change the color of the entire line of text.

### ISSUE THREAD

**Issue by scottming** [dracula/vim#326]
### What happened

I noticed that Dracula has some issues with the highlighting of diagnostics. When it receives a range, Dracula turns all the text within that range orange. Notice line 6 in the screenshot. This is very **disruptive** when editing code and has poor readability. Nowadays, almost all LSPs return diagnostics in real-time, and returning a range for an entire line is very common.

![image](https://github.com/user-attachments/assets/c23db89f-a3d6-44b5-bd16-b8f3f409ce98)

### What I expected to happen

What I want is an effect like One Dark, where only the wavy underline is changed, instead of changing the color of all the text.

![Discord 2024-07-18 15 50 34](https://github.com/user-attachments/assets/01b889f5-adc8-49bb-a767-5c570658224f)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**:
- **Vim version**: nvim 0.10
- **OS**: mac
- **Terminal/Terminal Emulator/VTE**: alacritty 0.13

- **`TERM` environment variable**:

**Comment by benknoble** [comment]
@stnley  or @I-Want-To-Believe is this in your wheel house? Maybe @dsifford ? I directed @scottming here hoping we could get some more eyes with better expertise on this. 

Apparently it used to look as desired; @scottming if you have time to try bisecting this repo to see what changed, that would be helpful. It may have been a change in Vim or Neovim, though, in which case that won't find anything.

**Comment by stnley** [comment]
I believe the reason is https://github.com/neovim/neovim/pull/22382

When [checking for special attribute support](https://github.com/dracula/vim/blob/ada471d684d4acfe803c4e033d7c3ae5d7252db6/colors/dracula.vim#L93) we use `has('gui_running')`. This returns `0` and `1` when running neovim in TUI and GUI (nvim-qt) respectively.

Setting `g:dracula_full_special_attrs_support = 1` appears to fix the issue, however the colors aren't displaying quite right on every terminal (foot doesn't work, kitty works). That could be unrelated, I'll test some more.

Kitty with `g:dracula_full_special_attrs_support = 0`
![1721529488_grimshot](https://github.com/user-attachments/assets/72bd4f4f-ad61-48c2-b61b-8cad646e1edf)


Kitty with `g:dracula_full_special_attrs_support = 1`
![1721529504_grimshot](https://github.com/user-attachments/assets/3a99f3cb-2f88-40cd-ad11-3ff297015902)

nvim-qt
![1721524326_grimshot](https://github.com/user-attachments/assets/0c3b0fdf-eb58-4be6-a824-7511a8f056e6)

@scottming could you try setting that variable and let me know if it works for you?

**Comment by stnley** [comment]
Sorry, I noticed you included you mentioned you're using alacritty. It appears to have the same issue foot has, the colors aren't quite right.

![1721529832_grimshot](https://github.com/user-attachments/assets/caace2ba-0727-45ad-8a8e-e885df0ad757)

**Comment by scottming** [comment]
@stnley Yes, this configuration solves the problem. Thank you. This is the effect I wanted.

![Uploading CleanShot 2024-07-21 at 12.03.47@2x.png…]()

**Comment by benknoble** [comment]
I can confirm that Alacritty's undercurl (when using `let g:dracula_full_special_attrs_support = 1`) uses the syntax color of the underlying text, not the highlight color. I get a squiggle, though, not a solid bar. Thanks @stnley for taking a look!
