### ISSUE TITLE
colorscheme in use different than expected value

### ISSUE THREAD

**Issue by matthewspencer** [dracula/vim#79]
### What happened

I have an issue with the colorscheme and syntax highlighting where the values represented are different than expected. For examples PHP class names are rendered as `DraculaFg` but defined as `DraculaCyan`.

### What I expected to happen

Below are screenshots comparing Dracula in vim to Dracula in Sublime Text. Reading through dracula.vim it looks like the values are set to match what is represented in the Sublime Text window.

NB: I’m fairly new to using vim full time so it is entirely possible I’m missing something obvious. Also if this isn’t the right forum for this kind of question lmk.

### Screenshot
![image](https://user-images.githubusercontent.com/97460/40029058-6febe004-57b0-11e8-895a-4d0987dfe858.png)

![image](https://user-images.githubusercontent.com/97460/40029098-a3daaeb8-57b0-11e8-9725-2ab0d19a37cf.png)

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: `vim`
- **Vim version**: version 8.0.1600
- **OS**: `Darwin localghost.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
- **Terminal/Terminal Emulator/VTE**: iTerm2 Build 3.1.6
- **`TERM` environment variable**: `xterm-256color`

### Additional Info

- `termguicolors` is set
- `:echo &t_Co` gives me `256`
- `COLORTERM` is set to `truecolor`

**Comment by dsifford** [comment]
Hi @matthewspencer,

No worries, questions are totally fine here.

In short, you're correct. There is not a perfect 1:1 match for vim syntax and sublime text syntax.

This is because the implementation of how the syntaxes are serialized and parsed out are vastly different between the two implementations. Sublime text (and Atom, and VSCode) use the same syntax algorithm as TextMate, so they are all able to share `.tmLanguage` files. This is nice because it allows those editors the ability to match together 100% if the themers target the same scoped syntax groups with the same colors.

To speak directly at the syntaxes disparities in the syntaxes in your examples:

**PHP:**
- Namespaces currently don't have any highlight scope, so that's not possible.
- `<?php` and `?>` are probably fixable, I'll look into that soon.
- `self` and constants are not scoped.
- functions/method names aren't scoped, **BUT** I've emailed the syntax maintainer about this and he plans on adding support soon (he responded literally today).  

**Javascript:**
- Class names should be fixable. I'll take a look at that soon.
- Function variables aren't fixable because that requires a wayyyy more advanced syntax parser than vim has right now.
- Proto chains aren't fixable currently either.

It's not all bad news though. Here's 2 little points of potential good news:

1. I am the maintainer of the VSCode Dracula theme and my goal since becoming a maintainer here is to create as close to perfect uniformity as I can between the two editors. It's close, but as you've seen, not totally perfect.
2. If you ever decide to switch to Neovim, the Neovim core contributors added implementing [Tree Sitter syntax parsing](https://github.com/neovim/neovim/issues/1767#issuecomment-353728712) to the roadmap, which will allow any tree sitter languages (currently JavaScript, TypeScript, and a few others) to be parsed identically when implemented (though this is not now, and maybe ever, a possibility with Sublime. Atom uses it currently and VSCode is talking about it).

### Note to self

**TODO:**
- [ ] See if `<?php` and `?>` are fixable without breaking other things.
- [ ] See if JS class names are fixable.

**Comment by matthewspencer** [comment]
Thanks @dsifford this is massively helpful! Also it proves I’m not totally crazy. Really appreciate your help. I’ll keep an eye on Neovim. I learned a bunch debugging this!

**Comment by benknoble** [comment]
Notes:

1. `php` tags are used to define `phpRegion`, but not actually scoped to a specific group (they get highlighted by the `Delimiter` group, which uses `DraculaFg`. Fixing this would require an update to the syntax file.
2. With pangloss/vim-javascript, `jsClassDefinition` is linked to `jsFuncName`, which is why they have the same highlight. This could probably be solved by linking `jsClassDefinition` ourselves. But note that none of these groups are available without pangloss/vim-javascript.
