### ISSUE TITLE
Airline tabline no colors latest update

### ISSUE THREAD

**Issue by aalvarado** [dracula/vim#97]
![tabline-broken](https://user-images.githubusercontent.com/370322/43016947-61d5913a-8c09-11e8-82c2-6b0e72e80fca.PNG)

![tabline-ok](https://user-images.githubusercontent.com/370322/43016959-65cbf496-8c09-11e8-818e-f0ec5de24d41.PNG)

if I set my plugin like this, tabline looks like the last image
```
  Plug 'dracula/vim', { 'as': 'dracula', 'commit': '918c67a' }
```

vimrc is here: https://gist.github.com/aalvarado/60643e8840b70825b3aa0125366c9eed

**Comment by dsifford** [comment]
@aalvarado Yeah, we adjusted the colors for tabline because we thought the bright purple was sort of confusing when trying to quickly figure out which split is active.

I'm open to adjusting some more though. There were only two of us discussing this back when the change was made.

If you don't mind, could you maybe read through and chime in to #92 and we'll go from there?

**Comment by aalvarado** [comment]
I'll check it out, thanks!
